/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#424432',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1d1d03',
        'secondary-container': '#fed65b',
        'surface-bright': '#fefccf',
        'on-secondary-fixed': '#241a00',
        'surface-dim': '#dedcb1',
        'surface-container': '#f2f0c4',
        'on-tertiary-fixed': '#1b1d0e',
        'inverse-primary': '#ffb3b5',
        'outline': '#8e706b',
        'on-primary-fixed-variant': '#8f0f28',
        'surface-container-highest': '#e6e5b9',
        'on-tertiary-fixed-variant': '#474836',
        'surface-container-high': '#eceabe',
        'error-container': '#ffdad6',
        'error': '#ba1a1a',
        'surface': '#fefccf',
        'on-primary-fixed': '#40000b',
        'outline-variant': '#e3beb8',
        'primary-container': '#870825',
        'on-primary': '#ffffff',
        'primary': '#600016',
        'on-secondary-fixed-variant': '#574500',
        'inverse-on-surface': '#f5f3c7',
        'tertiary-fixed': '#e4e4cc',
        'background': '#fefccf',
        'secondary': '#735c00',
        'on-surface': '#1d1d03',
        'on-tertiary': '#ffffff',
        'surface-tint': '#af2b3e',
        'tertiary-fixed-dim': '#c8c8b0',
        'on-primary-container': '#ff8e94',
        'surface-container-low': '#f8f6c9',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#5a403c',
        'on-secondary-container': '#745c00',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#ffb3b5',
        'inverse-surface': '#323214',
        'on-tertiary-container': '#b0b19a',
        'tertiary': '#2c2e1d',
        'primary-fixed': '#ffdada',
        'surface-variant': '#e6e5b9',
      },
      fontFamily: {
        'headline': ['Noto Serif', 'serif'],
        'body': ['Newsreader', 'serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [],
}
